// DOM integration tests; fixtures are deliberately synthetic, never published as market data.
const {JSDOM}=require('jsdom');
const fs=require('node:fs');
const assert=require('node:assert/strict');
const html=fs.readFileSync('index.html','utf8'),code=fs.readFileSync('app.js','utf8');
const base={isin:'INE000000001',symbol:'TEST',name:'Synthetic Test Company',sector:'Test industry',asof:'2026-09-18',last:114,r5:4,r20:12,r60:18,rs20:10,rs60:15,turnover_cr:12,participation:2,volume_ratio_5d_30d:2.25,turnover_20d_cr:28.9,mcap_cr:2096,turnover_mcap_20d_pct:1.379,up_volume_share_20:62,extension:3,candidate:true,setup:'Confirmed moves',stage:'Confirmed move',rotation_posture:'Sector-supported setup',momentum_confirmations:4,momentum_checks:['VStop bullish','OBV MACD bullish','Directional trend','Efficient advance'],vstop:108,vstop_bullish:true,vstop_distance:5.5,obv_bullish:true,obv_flip:false,adx:31,plus_di:29,minus_di:12,efficiency_20:.55,atr_pct:2.1,theme_name:'Test theme',theme_state:'Leading',theme_rank:1,theme_taxonomy:'Curated theme',theme_breadth_change:10,industry_name:'Test industry',industry_rank:1,stock_vs_industry_r20:2,theme_memberships:[{name:'Test theme',state:'Leading',rank:1}],anchor:110,anchor_adjusted:110,leader:true,reasons:['Held above reference'],risks:['Synthetic test'],tracking:null};
Object.assign(base,{score_version:'review-priority-v1-shadow',priority_rank:1,priority_denominator:1,priority_score:76,strength_rank:1,strength_denominator:3,strength_score:84,score_positives:['efficient trend'],score_concerns:['extension risk']});
const other={...base,isin:'INE000000002',symbol:'OTHER',name:'Other Test Company',candidate:false,setup:'Other',stage:'Trend intact',leader:false,scanner_eligible:true,analysis_available:true,priority_rank:null,priority_denominator:null,priority_score:null,priority_na_reason:'not a current confirmed candidate',strength_rank:2,strength_score:72};
const context={...base,isin:'INE000000003',symbol:'THIN',name:'Thin Test Company',candidate:false,setup:'Other',stage:'Trend intact',leader:false,r20:20,scanner_eligible:false,analysis_available:true,eligibility_reason:'below liquidity requirement',priority_rank:null,priority_denominator:null,priority_score:null,priority_na_reason:'below liquidity requirement',strength_rank:3,strength_score:66};
const snapshot={schema:1,model:'confirmed-v3-industry-rank',status:'ready',asof:'2026-09-18',snapshot_id:'test-snapshot',policy:{benchmark:'^CRSLDX',benchmark_name:'Nifty 500'},rows:[base,other],analysis_rows:[base,other,context],themes:[{name:'Test theme',taxonomy:'Curated theme',members:[base.isin,'INE000000002','INE000000003'],status:'Leading',rank:1,rank_change:1,r20:12,r60:20,breadth:80,breadth_change:10,vstop_bullish:75,resolved:2,total:3,coverage_quality:'Broad',rs20:10,rs60:15}],rotation:{leaders:['Test theme'],review:[]},summary:[],tracking:[],market:{benchmark:'Nifty 500',ticker:'^CRSLDX',r20:2,breadth:60,regime:'Bull'},coverage:{fresh:3,universe:3,analysed:3,eligible:2,reasons:{'below liquidity requirement':1}},excluded:[{isin:'INE000000003',symbol:'THIN',name:'Thin Test Company',sector:'Test industry',reason:'below liquidity requirement',analysis_available:true}]};
async function boot(data=snapshot,chartDate=data.asof,research=null,chunked=false){
 const dom=new JSDOM(html,{url:'https://example.test/Stocks/',runScripts:'outside-only'}),w=dom.window;
 w.HTMLDialogElement.prototype.showModal=function(){this.open=true};
 w.HTMLDialogElement.prototype.close=function(){this.open=false;this.dispatchEvent(new w.Event('close'))};
 const chart={dates:['2026-01-02','2026-09-18'],o:[100,112],h:[103,115],l:[99,110],c:[102,114],v:[900,1000],vstop:[98,108]};
 const chartSet={[base.isin]:chart,INE000000002:{...chart,c:[101,113]},INE000000003:{...chart,c:[99,100]}};
 w.fetch=async url=>{if(chunked){if(url.includes('current.json'))return {ok:true,json:async()=>({schema:1,base:'snapshots/unit/',charts:'charts/index.json'})};if(url.includes('charts/index.json'))return {ok:true,json:async()=>({schema:1,asof:chartDate,snapshot_id:'test-snapshot',files:Object.fromEntries(Object.keys(chartSet).map(id=>[id,'00.json']))})};if(url.includes('charts/00.json'))return {ok:true,json:async()=>({schema:1,asof:chartDate,snapshot_id:'test-snapshot',charts:chartSet})};if(url.includes('latest.json'))return {ok:true,json:async()=>data};if(url.includes('health.json'))return {ok:true,json:async()=>({status:'ok',snapshot_id:'test-snapshot'})};}if(url.includes('charts.json'))assert.match(url,/snapshot=test-snapshot/);return {ok:true,json:async()=>url.includes('backtest')?research:url.includes('latest')?data:url.includes('health')?{status:'ok'}:{asof:chartDate,snapshot_id:'test-snapshot',charts:chartSet}};};
 w.eval(code);await new Promise(r=>setImmediate(r));return {dom,w,d:w.document};
}
(async()=>{
 let {dom,w,d}=await boot();
 assert.match(d.querySelector('thead').textContent,/Rank \/ score/);
 assert.equal(d.querySelectorAll('#stock-rows tr').length,1,'default only confirmed');
 assert.match(d.querySelector('#stock-rows').textContent,/#1 of 1.*Fresh-entry priority · 76\/100.*Strength #1 of 3/s);
 d.querySelector('[data-watch]').click();assert.equal(JSON.parse(w.localStorage.getItem('stocks-workspace-v1'))[base.isin].watch,true);
 d.querySelector('[data-stock]').click();await new Promise(r=>setImmediate(r));
 assert.equal(d.querySelector('#stock-dialog').open,true);assert.ok(d.querySelector('#detail-chart svg'));
 assert.match(d.querySelector('#detail-content').textContent,/VStop 10×2/);
 assert.match(d.querySelector('#detail-content').textContent,/OBV MACD/);
 assert.match(d.querySelector('.rank-panel').textContent,/Fresh-entry priority.*#1 of 1.*76\/100.*Descriptive strength.*#1 of 3.*84\/100/s);
 assert.match(d.querySelector('#detail-content').textContent,/requires VStop and OBV MACD to both be bearish/);
 assert.match(d.querySelector('#detail-content').textContent,/Volume 5D\/30D: 2.25×/);
 assert.match(d.querySelector('#detail-content').textContent,/1.4% of live market cap/);
 const svg=d.querySelector('#detail-chart svg'),cross=d.querySelector('.chart-cross');
 const vstop=svg.querySelector('.vstop');assert.ok(Number(vstop.getAttribute('y1'))>=35&&Number(vstop.getAttribute('y1'))<=252,'VStop is inside the price scale');
 svg.getBoundingClientRect=()=>({left:0,top:0,width:900,height:370});
 svg.dispatchEvent(new w.MouseEvent('mousemove',{clientX:100,clientY:100}));
 assert.equal(cross.hidden,false);assert.match(d.querySelector('.chart-legend').textContent,/O 100.00/);
 svg.dispatchEvent(new w.MouseEvent('mouseleave'));assert.equal(cross.hidden,true);
 let note=d.querySelector('#stock-note');note.value='Check earnings';note.dispatchEvent(new w.Event('input'));
 assert.equal(JSON.parse(w.localStorage.getItem('stocks-workspace-v1'))[base.isin].note,'Check earnings');
 d.querySelector('[data-review="dismissed"]').click();assert.equal(d.querySelectorAll('#stock-rows tr').length,0);
 d.querySelector('[data-review="unreviewed"]').click();d.querySelector('#stock-dialog').close();
 d.querySelector('[data-view="watchlist"]').click();assert.equal(d.querySelectorAll('#stock-rows tr').length,1);
 assert.equal(d.querySelector('#all-charts').hidden,false);d.querySelector('#all-charts').click();await new Promise(r=>setImmediate(r));
 assert.equal(d.querySelectorAll('.bulk-chart-card').length,1);assert.match(d.querySelector('#bulk-chart-note').textContent,/1 January 2026/);assert.match(d.querySelector('.chart-caption').textContent,/2026-01-02 to 2026-09-18/);
 d.querySelector('#charts-back').click();
 d.querySelector('[data-view="custom"]').click();
 const upload=d.querySelector('#custom-import'),file={name:'Blue list.txt',size:50,text:async()=> 'NSE:OTHER,NSE:TEST,BSE:UNKNOWN'};Object.defineProperty(upload,'files',{value:[file],configurable:true});upload.dispatchEvent(new w.Event('change'));await new Promise(r=>setImmediate(r));
 assert.equal(d.querySelectorAll('#stock-rows tr').length,2);assert.match(d.querySelector('#empty').textContent,/BSE:UNKNOWN.*BSE-only analysis/s);assert.deepEqual(JSON.parse(w.localStorage.getItem('stocks-custom-watchlist-v1')),['OTHER','TEST','BSE:UNKNOWN']);
 d.querySelector('#all-charts').click();await new Promise(r=>setImmediate(r));assert.equal(d.querySelectorAll('.bulk-chart-card').length,2);assert.match(d.querySelector('.bulk-chart-card .company-button').textContent,/OTHER/);d.querySelector('#charts-back').click();
 d.querySelector('[data-view="themes"]').click();d.querySelector('#theme-grid [data-theme]').click();assert.equal(d.querySelectorAll('#stock-rows tr').length,3,'theme shows every registered member');
 assert.match(d.querySelector('#stock-rows tr').textContent,/Scanner highlight/);assert.match(d.querySelector('#stock-rows').textContent,/THIN.*Theme outperformer.*Context only/s);
 assert.equal(d.querySelector('#all-charts').hidden,false);
 assert.match(d.querySelector('#all-charts').textContent,/3/);d.querySelector('#all-charts').click();await new Promise(r=>setImmediate(r));assert.equal(d.querySelectorAll('.bulk-chart-card').length,3);assert.match(d.querySelector('#bulk-chart-grid').textContent,/THIN.*Theme outperformer/s);d.querySelector('#charts-back').click();
 d.querySelector(`[data-watch="${context.isin}"]`).click();d.querySelector('[data-view="watchlist"]').click();assert.match(d.querySelector('#all-charts').textContent,/2/);d.querySelector('#all-charts').click();await new Promise(r=>setImmediate(r));assert.equal(d.querySelectorAll('.bulk-chart-card').length,2,'context-only saved stock remains in All charts');d.querySelector('#charts-back').click();d.querySelector('[data-view="themes"]').click();d.querySelector('#theme-grid [data-theme]').click();
 assert.match(d.querySelector('#rotation-board').textContent,/Test theme/);
 d.querySelector('#clear-theme').click();assert.equal(d.querySelectorAll('#stock-rows tr').length,2);
 let search=d.querySelector('#search');search.value='OTHER';search.dispatchEvent(new w.Event('input'));assert.equal(d.querySelectorAll('#stock-rows tr').length,1);assert.match(d.querySelector('#stock-rows').textContent,/Other Test/);
 w.fetch=async()=>{throw Error('offline')};d.querySelector('#reload').click();await new Promise(r=>setImmediate(r));assert.equal(d.querySelectorAll('#stock-rows tr').length,1,'failed browser refresh preserves loaded rows');assert.match(d.querySelector('#health').textContent,/Browser refresh failed.*offline/s);assert.doesNotMatch(d.querySelector('#health').textContent,/First scan pending/);
 dom.window.close();
 ({dom,w,d}=await boot(snapshot,snapshot.asof,null,true));d.querySelector('[data-stock]').click();await new Promise(r=>setImmediate(r));assert.ok(d.querySelector('#detail-chart svg'),'immutable chart chunk renders');dom.window.close();
 ({dom,w,d}=await boot({schema:1,status:'awaiting_first_scan',asof:null,policy:{benchmark:'^CRSLDX'},rows:[],themes:[],tracking:[],summary:[]}));
 assert.match(d.querySelector('#empty').textContent,/Waiting for the first/);assert.equal(d.querySelectorAll('#stock-rows tr').length,0);assert.match(d.querySelector('#stats').textContent,/—/);dom.window.close();
 ({dom,w,d}=await boot(snapshot,'2026-09-17'));d.querySelector('[data-stock]').click();await new Promise(r=>setImmediate(r));assert.match(d.querySelector('#detail-chart').textContent,/snapshots differ/);dom.window.close();
 const report=JSON.parse(fs.readFileSync('data/backtest/report.json','utf8'));report.model='confirmed-v3-industry-rank';report.benchmark={...report.benchmark,name:'Nifty 500',ticker:'^CRSLDX'};
 ({dom,w,d}=await boot({...snapshot,freshness:'delayed',expected_session:'2026-09-21',tracking:[{isin:'INE000000004',symbol:'NO_LONGER_ELIGIBLE',setup:'Confirmed moves',first_seen:'2026-09-01',state:'Below breakout level',outcomes:{'5':{best_excursion:6,worst_excursion:-7,net:-3,'5_before_minus5':'ambiguous_same_session'}}}]},snapshot.asof,report));
 d.querySelector('[data-view="evidence"]').click();
 assert.match(d.querySelector('#historical-upside').textContent,/Reached \+5%/);
 assert.equal(d.querySelectorAll('#historical-upside tbody tr').length,report.results.holdout.length);
 assert.match(d.querySelector('#journal').textContent,/NO_LONGER_ELIGIBLE/);
 assert.match(d.querySelector('#journal').textContent,/ambiguous same session/);
 assert.equal(d.querySelector('#journal [data-stock]'),null,'unavailable stock is still recorded without a broken detail link');
 assert.match(d.querySelector('#health').textContent,/Delayed snapshot/);
 assert.doesNotMatch(d.body.textContent,/\bpp\b|percentage points|Midcap 150/);
 assert.equal(d.querySelector('#historical-research').parentElement.tagName,'DETAILS');
 dom.window.close();
 console.log('UI integration passed: confirmed defaults, saved/custom watchlists, multi-chart grids, notes, review, theme filter, search, pending state and mismatched charts.');
})().catch(e=>{console.error(e);process.exitCode=1});
